### PR TITLE
Named results support

### PR DESCRIPTION
**Pull request by rails-to-cosmos**

### CODE REVIEW

**Comment by astahlman** [comment]
Looks like the tests are choking on `(void-function string-trim)`. Maybe we just need to `(require 'subr-x)`?

For the acceptance test, I think we could just add one similar to the [existing test](https://github.com/astahlman/ob-async/blob/master/ob-async.org#execute-a-named-block) but with the #+RESULTS block at the top of the buffer. What do you think?

**Comment by rails-to-cosmos** [comment]
Okay, I'll fix this, thank you :)

**Comment by rails-to-cosmos** [comment]
Check it out, please.

**Comment by astahlman** [comment]
:tada: Merged, thanks! :tada:

**Pull request merged**
