### PR TITLE
Inherit :dir header arg in async function for remote execution

### LINKED ISSUE #8: Execute asynchronous processes on remote host
Is it possible to execute the code block on a remote host? I tried to use the `:dir` header argument with a tramp file link but this didn't work. I guess `async-start` would have to spawn the emacs instance on the remote and not the local host but I am not sure if it can be done.

### PR DESCRIPTION
**Pull request by stnutt**
This fixes #8. The default directory wasn't being set (from the :dir header arg) inside of the async function, so that meant you couldn't execute blocks asynchronously on remote hosts or using sudo.

### CODE REVIEW

**Comment by astahlman** [comment]
Ahhh, I see. Good catch, and thanks for the PR!

The change looks good, but can you make it in `ob-async.org` and tangle it to `ob-async.el`? The source is here: https://github.com/astahlman/ob-async/blob/master/ob-async.org#definition. Sorry for the runaround.

I was trying to think of a good way to write an acceptance test for this, but I think the problem only surfaces when using TRAMP, right? Unfortunately I can't think of anything that doesn't involve actually making some kind of remote connection.

**Comment by stnutt** [comment]
Sure, I'll modify the Org file instead and tangle it. As far as writing a test, I've written one that just sets :dir to / and echos the pwd, but that passes without my change since default-directory is already set around the call to async-start, so it's tramp or nothing. Unfortunately, I'm not aware of a tramp method that could be used in a testing situation.

**Comment by astahlman** [comment]
Ah, very clever! Just tested with `$USER`, and confirmed that the following works. Yeah, I think that would be a great test.

```
#+BEGIN_SRC sh :async :dir /sudo:$USER@localhost:/
  echo "$SUDO_USER $PWD"
#+END_SRC
```

**Comment by stnutt** [comment]
My commit is updated with the test case and with all changes made in the org file and also tangled. I had to change the travis config to have sudo installed, and the CI is passing with the new test case.

**Comment by astahlman** [comment]
Merged. Thanks for the change!

**Pull request merged**
